# Generated by Django 5.1.1 on 2024-10-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='creator',
            field=models.IntegerField(default=0),
        ),
    ]
