# Generated by Django 5.1.1 on 2024-10-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tournament_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
