# Generated by Django 5.1.1 on 2024-10-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_participation_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='display_name',
        ),
    ]
