# Generated by Django 5.1.1 on 2024-10-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_participation_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='display_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
