# Generated by Django 5.1.1 on 2024-10-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_gameevent_game_remove_gameevent_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match4',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished')], default='PENDING', max_length=20),
        ),
    ]
