# Generated by Django 5.1.3 on 2024-11-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_friendrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='invite_status',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Pending'), (2, 'Accepted'), (3, 'Cancelled'), (4, 'Rejected')], default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='message_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.IntegerField(choices=[(0, 'Text'), (1, 'Game Invite')], default=0),
        ),
    ]
