# Generated by Django 5.1.1 on 2024-10-01 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='avatars/')),
                ('friends', models.CharField(blank=True, max_length=200, null=True)),
                ('friends_wait', models.CharField(blank=True, max_length=200, null=True)),
                ('friends_request', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.CharField(blank=True, max_length=200, null=True)),
                ('friends_wait', models.CharField(blank=True, max_length=200, null=True)),
                ('friends_request', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
