# Generated by Django 5.1.1 on 2024-10-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='friends_blocked',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='user_42',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='friends_blocked',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_42',
            field=models.BooleanField(default=False),
        ),
    ]
