# Generated by Django 5.1.1 on 2024-10-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_apiuser_user_42_alter_user_user_42'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='oauth_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='oauth_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
