# Generated by Django 5.1.1 on 2024-10-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apiuser_oauth_id_user_oauth_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
