# Generated by Django 5.1.1 on 2024-10-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_apiuser_two_factor_enabled_apiuser_two_factor_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='two_factor_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_configured',
            field=models.BooleanField(default=False),
        ),
    ]
