# Generated by Django 5.1.1 on 2024-10-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_avatar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_image',
        ),
    ]
