# Generated by Django 5.1.2 on 2024-10-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_apiuser_avatar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='display_name',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
