# Generated by Django 5.1.2 on 2024-10-29 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_apiuser_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='friends_blocked',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='friends_request',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='friends_wait',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends_blocked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends_request',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends_wait',
        ),
    ]
